### ISSUE TITLE
Support libraries and inherited contracts

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/truffle-debugger#39]

**Comment by boorac** [comment]
Any kind of ETA on this? =)

**Comment by gnidan** [comment]
@boorac this will go out with the next release

**Comment by seesemichaelj** [comment]
@gnidan ETA on the next release? :D

**Comment by chupd** [comment]
Hi. guy~

v4.1.5 still have that issue. ( https://github.com/trufflesuite/truffle/issues/655#event-1547103790)

**Comment by vardhmanandroid2015** [comment]
I am facing the same issue - 
Truffle version - 4.1.6 Solidity compiler (solcjs - 0.4.21)

debug(develop:0xac56e902...)>
redux-saga error: uncaught at session.saga
at session.saga
 at controller.saga
 at stepNext
 TypeError: Cannot read property 'line' of undefined
    at D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\truffle-core\~\truffle-debugger\dist\debugger.js:610:1
    at D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\reselect\lib\index.js:76:1
    at D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\reselect\lib\index.js:36:1
    at D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\reselect\lib\index.js:90:1
    at D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\reselect\lib\index.js:36:1
    at D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\reselect\lib\index.js:86:1
    at D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\reselect\lib\index.js:36:1
    at D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\reselect\lib\index.js:86:1
    at D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\reselect\lib\index.js:36:1
    at runSelectEffect (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\proc.js:698:1)
    at runEffect (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\proc.js:435:1)
    at next (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\proc.js:315:1)
    at currCb (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\proc.js:388:1)
    at takeCb (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\proc.js:466:1)
    at Object.put (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\channel.js:73:1)
    at D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\channel.js:161:1
    at Array.<anonymous> (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\channel.js:182:1)
    at Object.emit (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\channel.js:26:1)
    at D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\middleware.js:67:1
    at dispatch (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux\es\applyMiddleware.js:35:1)
    at D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\utils.js:250:1
    at D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\proc.js:489:1
    at exec (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\scheduler.js:19:1)
    at flush (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\scheduler.js:60:1)
    at asap (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\scheduler.js:33:1)
    at Array.<anonymous> (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\channel.js:185:1)
    at Object.emit (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\channel.js:26:1)
    at Object.dispatch (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\middleware.js:67:1)
    at Session.dispatch (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\truffle-core\~\truffle-debugger\dist\debugger.js:2684:1)
    at Session.stepNext (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\truffle-core\~\truffle-debugger\dist\debugger.js:2701:1)
    at Object.interpreter (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\truffle-core\lib\commands\debug.js:358:1)
    at ReplManager.interpret (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\truffle-core\lib\repl.js:119:1)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)

**Comment by gnidan** [comment]
@vardhmanandroid2015 that's likely a different error, but try upgrading to Truffle v4.1.8. It should be fixed there.

**Comment by vardhmanandroid2015** [comment]
Updated to truffle v4.1.8 Now getting into new error - I have tried to unbox webpack in another project at the same location where my previous project was....Please let me know If requires any additional information to provide any pointer... 

Gathering transaction data...

redux-saga error: uncaught at session.saga
at session.saga
 at recordInstance
 TypeError: Cannot read property 'context' of null
    at Object.addInstance$ (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\truffle-core\~\truffle-debugger\dist\debugger.js:5533:1)
    at tryCatch (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\regenerator-runtime\runtime.js:62:15)
    at Generator.invoke [as _invoke] (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\regenerator-runtime\runtime.js:296:1)
    at Generator.prototype.(anonymous function) [as next] (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\regenerator-runtime\runtime.js:114:1)
    at tryCatch (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\regenerator-runtime\runtime.js:62:15)
    at maybeInvokeDelegate (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\regenerator-runtime\runtime.js:358:1)
    at Generator.invoke [as _invoke] (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\regenerator-runtime\runtime.js:270:1)
    at Generator.prototype.(anonymous function) [as next] (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\regenerator-runtime\runtime.js:114:1)
    at next (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\proc.js:311:1)
    at currCb (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\proc.js:388:1)
    at runSelectEffect (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\proc.js:699:1)
    at runEffect (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\proc.js:435:1)
    at next (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\proc.js:315:1)
    at proc (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\proc.js:270:1)
    at resolveIterator (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\proc.js:456:1)
    at runCallEffect (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\proc.js:517:1)
    at runEffect (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\proc.js:435:1)
    at D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\proc.js:644:1
    at Array.forEach (native)
    at runAllEffect (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\proc.js:643:1)
    at runEffect (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\proc.js:435:1)
    at next (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\proc.js:315:1)
    at currCb (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\proc.js:388:1)
    at checkEffectEnd (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\proc.js:612:1)
    at chCbAtKey (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\proc.js:627:1)
    at Object.currCb [as cb] (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\proc.js:388:1)
    at D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\proc.js:358:1
    at Array.forEach (native)
    at end (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\proc.js:357:1)
    at Object.task.cont (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\proc.js:99:1)
    at next (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\proc.js:321:1)
    at currCb (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\proc.js:388:1)
    at takeCb (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\proc.js:466:1)
    at Object.put (D:\YoutubeVideos\01-Truffle\node_modules\truffle\build\webpack:\~\redux-saga\es\internal\channel.js:73:1)

**Comment by vardhmanandroid2015** [comment]
I created all together new project in different location with new installation for truffle 4.1.18 & seems to be working as expected....
Is it recommended that we should not be creating multiple decentralized application project at same location hitting to same installation of truffle.......I think so as cleaned up did the magic....

**Comment by gnidan** [comment]
@vardhmanandroid2015 the problem is that `truffle debug` re-runs compilation every time, so if you previously compiled your contracts with an earlier version of Solidity, it fails to match the two different versions of bytecode. You can do what you want, just make sure to run `truffle migrate --reset --compile-all`

**Comment by HarryR** [comment]
I'm still encountering this bug, bug it goes deeper than as described in this ticket and I may have found a better description of the underlying problem with Ganache.

The problem is that `getReceipt` is returning `null` even though the transaction exists... The `Cannot read property 'context' of null`.

But the weird problem is that the transaction is submitted via a jsonrpc client, which waits for the transaction receipt, this uses the same connection.

Then when other jsonrpc clients try to fetch the receipt, it returns null/None.

There is more detail in this ticket: https://github.com/clearmatics/ion/issues/80

I don't think this problem is in `truffle-debugger`, but is somewhere in the ganache-cli core.
